export const rewardsList = [
	{
		id: 14,
		place: 15,
		price: "100 000",
		className: "rounded-3 text-left px-2 m-auto text-light",
	},
	{
		id: 13,
		place: 14,
		price: "50 000",
		className: "rounded-3 text-left px-2 m-auto text-warning",
	},
	{
		id: 12,
		place: 13,
		price: "30 000",
		className: "rounded-3 text-left px-2 m-auto text-warning",
	},
	{
		id: 11,
		place: 12,
		price: "20 000",
		className: "rounded-3 text-left px-2 m-auto text-warning",
	},
	{
		id: 10,
		place: 11,
		price: "10 000",
		className: "rounded-3 text-left px-2 m-auto text-warning",
	},
	{
		id: 9,
		place: 10,
		price: "5 000",
		className: "rounded-3 text-left px-2 m-auto text-light",
	},
	{
		id: 8,
		place: 9,
		price: "3 000",
		className: "rounded-3 text-left px-2 m-auto text-warning",
	},
	{
		id: 7,
		place: 8,
		price: "2 000",
		className: "rounded-3 text-left px-2 m-auto text-warning",
	},
	{
		id: 6,
		place: 7,
		price: "1 500",
		className: "rounded-3 text-left px-2 m-auto text-warning",
	},
	{
		id: 5,
		place: 6,
		price: "1 000",
		className: "rounded-3 text-left px-2 m-auto text-warning",
	},
	{
		id: 4,
		place: 5,
		price: "500",
		className: "rounded-3 text-left px-2 m-auto text-light",
	},
	{
		id: 3,
		place: 4,
		price: "400",
		className: "rounded-3 text-left px-2 m-auto text-warning",
	},
	{
		id: 2,
		place: 3,
		price: "300",
		className: "rounded-3 text-left px-2 m-auto text-warning",
	},
	{
		id: 1,
		place: 2,
		price: "200",
		className: "rounded-3 text-left px-2 m-auto text-warning",
	},
	{
		id: 0,
		place: 1,
		price: "100",
		className: "rounded-3 text-left px-2 m-auto text-warning",
	},
];
